# Generated by Django 4.1 on 2022-08-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                ("email", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=6)),
                ("income", models.IntegerField()),
                ("password", models.CharField(max_length=500)),
            ],
        ),
    ]
