# Generated by Django 4.1 on 2022-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="people",
            name="updated",
            field=models.BooleanField(default=False),
        ),
    ]
