# Generated by Django 4.1 on 2022-08-30 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_people_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="updated",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
